general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoid multiple instances of hyprlock
    unlock_cmd =                                # Command ran before unlock
    before_sleep_cmd = loginctl lock-session    # Lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # Turn monitors on after suspend
    ignore_dbus_inhibit = false                 # Ignore idle inhibits from browsers/vlc
    ignore_systemd_inhibit = false              # Ignore systemd inhibitors
}

# Screen Timeout: Dim monitor
listener {
    timeout = 150                               # 2.5 min
    on-timeout = brightnessctl -s set 10        # Set monitor backlight to 10%
    on-resume = brightnessctl -r                # Restore monitor backlight
}

# Screen Timeout: Turn off displays
listener {
    timeout = 300                               # 5 min
    on-timeout = hyprctl dispatch dpms off      # Turn off screen
    on-resume = hyprctl dispatch dpms on        # Turn on screen
}

# Suspend Timeout: Lock and sleep
listener {
    timeout = 600                               # 10 min
    on-timeout = systemctl suspend              # Suspend computer
}
